# Generated by Django 4.0.1 on 2022-01-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meetings',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='Groups',
            new_name='Meeting',
        ),
    ]
